---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Links:
  - IMDb:
    - href: https://www.imdb.com/
  - Weather:
    - href: http://weather.{{ domain }}

- Developemnt:
  - GitHub: 
    - icon: https://github.com/favicon.ico
      href: https://github.com
  - LiteLLM:
    - icon: http://{{ ip }}:4000/ui/favicon.ico
      href: http://{{ ip }}:4000/ui
  - ByteStash:
    - icon: http://bytestash.{{ domain }}/favicon.ico
      href: http://bytestash.{{ domain }}


- Social:
  - Telegram:
    - icon: https://web.telegram.org/z/favicon.svg
      href: https://web.telegram.org/
  - Linkedin:
    - icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/linkedin.png
      href: https://linkedin.com/
