---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Entertaiment:
  - IMDb:
    - href: https://www.imdb.com/

- Developemnt:
  - GitHub: 
    - icon: https://github.com/favicon.ico
      href: https://github.com
  - LiteLLM:
    - icon: http://{{ ip }}:4000/ui/favicon.ico
      href: http://{{ ip }}:4000/ui

- Social:
  - Telegram:
    - icon: https://web.telegram.org/z/favicon.svg
      href: https://web.telegram.org/
  - Linkedin:
    - icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/linkedin.png
      href: https://linkedin.com/
