---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Media:
    - Jellyfin:
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/jellyfin.svg
        href: http://jellyfin.{{ domain }}
        description: Movies streaming
        widget:
            type: jellyfin
            url: http://jellyfin.home_net:8096
            key: {{ jellyfin_api }}

    - Radarr:
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/radarr.svg
        href: http://radarr.{{ domain }}
        description: Movies library management
        widget:
            type: radarr
            url: http://radarr.home_net:7878
            key: {{ radarr_api }}

    - Sonarr:
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/sonarr.svg
        href: http://sonarr.{{ domain }}
        description: Series library management
        widget:
            type: sonarr
            url: http://sonarr.home_net:8989
            key: {{ sonarr_api }}

- Cloud:
    - NextCloud:
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/nextcloud.png
        href: http://nextcloud.{{ domain }}/
        description: Cloud drive
        widget:
            type: nextcloud
            url: http://nextcloud.home_net:80
            fields: [ "freespace" ]
            username: {{ nextcloud_user }}
            password: {{ nextcloud_password }}

    - PiHole:
        icon: http://pihole.{{ domain }}/admin/img/logo.svg
        href: http://pihole.{{ domain }}/admin/
        description: Ad-blocking DNS
        widget:
            type: pihole
            url: http://192.168.0.11:8001
            key: {{ pihole_api }}

    - OpenWebUI:
        icon: http://openwebui.{{ domain }}/static/favicon.svg
        href: http://openwebui.{{ domain }}/
        description: Chat with AI assistant

    - Paisa:
        icon: https://paisa.fyi/images/logo.svg
        href: http://budget.{{ domain }}/
        description: Finacial management application

    - Paperless:
        icon: http://paperless.{{ domain }}/favicon.ico
        href: http://paperless.{{ domain }}
        description: Document management system
