---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: 
        - /data
        - /media

- search:
    provider: google
    target: _blank
