- name: Setup couchdb
  hosts: all
  vars_files:
    - ../vars/secrets.yml
    - ../vars/versions.yml
    - ../vars/ports.yml
  tasks:
  - name: Create storage folder
    file:
      path: /data/couchdb
      state: directory
    become: true

  - name: Create docker home network
    docker_network:
      name: home_net 

  - name: Run couchdb container
    docker_container:
      name: couchdb 
      image: couchdb:{{ couchdb_version }}
      env:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: "{{ couchdb_admin_password }}"
      networks:
        - name: home_net
          aliases: couchdb
      published_ports:
        - "{{ couchdb_port }}:5984"
      restart_policy: always
      volumes:
        - "/data/couchdb:/opt/couchdb/data"
