- name: Build homepage
  hosts: all
  vars_files:
    - ../vars/keys.yml
    - ../vars/versions.yml
    - ../vars/ports.yml
    - ../vars/host.yml
  tasks:
    - name: Copy homepage config
      copy:
        dest: "/home/{{ ansible_user }}/"
        src: "../configs/homepage"

    - name: Place api keys
      template:
        src: ../configs/homepage/services.yaml
        dest: "/home/{{ ansible_user }}/homepage/services.yaml"

    - name: Create docker home network
      docker_network:
        name: home_net

    - name: Run homepage container
      docker_container:
        image: ghcr.io/gethomepage/homepage:{{ homepage_version }}
        name: homepage
        networks:
          - name: home_net
            aliases: homepage
        ports:
          - "{{ homepage_port }}:3000"
        volumes:
          - "/home/{{ ansible_user}}/homepage:/app/config"
          - "/data:/data:ro"
          - "/media:/media:ro"
        restart_policy: unless-stopped