- name: Install Nextcloud in docker
  hosts: all
  vars_files:
  - ../vars/secrets.yml
  tasks:
  - name: Create storage folder
    file:
      path: /data/nextcloud/storage
      state: directory
    become: true

  - name: Create db folder
    file:
      path: /data/nextcloud/db
      state: directory 
    become: true

  - name: Create docker home network
    docker_network:
      name: home_net

  - name: Create docker nextcloud network
    docker_network:
      name: nextcloud_net

  - name: Run postgress container
    docker_container:
      name: nextcloud_db
      image: arm64v8/postgres:14
      networks:
        - name: nextcloud_net
          aliases: nextcloud_db
      restart_policy: always
      env:
        POSTGRES_DB: nextcloud
        POSTGRES_USER: nextcloud
        POSTGRES_PASSWORD: "{{ nextcloud_pg_password }}"
      volumes:
        - "/data/nextcloud/db:/var/lib/postgresql/data"
  
  - name: Run nextcloud container
    docker_container:
      name: nextcloud
      image: arm64v8/nextcloud:26.0.0
      networks:
        - name: nextcloud_net
          aliases: nextcloud
        - name: home_net
          aliases: nextcloud
      published_ports:
        - 8000:80
      restart_policy: always
      env:
        POSTGRES_DB: nextcloud
        POSTGRES_USER: nextcloud
        POSTGRES_PASSWORD: "{{ nextcloud_pg_password }}"
        POSTGRES_HOST: nextcloud_db
        # It can be configured with env variables, but it didn't work for me.
        # NEXTCLOUD_ADMIN_USER: admin
        # NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      volumes:
        - "/data/nextcloud/storage:/var/www/html"
