- name: Deploy Open WebUI container
  hosts: all
  vars_files:
    - ../vars/ai.yml
    - ../vars/ports.yml
    - ../vars/versions.yml
  tasks:
    - name: Create directories
      file:
        path: "/data/openwebui"
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: yes

    - name: Deploy OpenWebUI container
      docker_container:
        name: openwebui
        image: ghcr.io/open-webui/open-webui:{{ openwebui_version }}
        restart_policy: always
        networks:
          - name: home_net
            aliases: openwebui
          - name: ai_net
            aliases: openwebui
        ports:
          - "{{ openwebui_port }}:8080"
        volumes:
          - "/data/openwebui:/app/backend/data"
