- name: Configure docker
  hosts: all
  become: true
  tasks:
  - name: Install required packages
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: latest
      update_cache: true

  - name: Ensure docker group exists
    group:
      name: docker
      state: present

  - name: Add user {{ansible_user}} to docker group
    user:
      name: "{{ansible_user}}"
      groups: docker
      append: yes

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Enable docker service
    systemd:
      name: docker.service
      enabled: true
      daemon_reload: true

  - name: Enable docker socket
    systemd:
      name: docker.socket
      enabled: true
      daemon_reload: yes
